<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>simpleroomcast</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimpleRoomCast.Core\SimpleRoomCast.Core.csproj" />
  </ItemGroup>
</Project>
